// Realistic placeholder data used when the API is unreachable so public pages
// never crash and always show something meaningful.

export const MOCK_LISTINGS = [
  {
    id: 1,
    slug: 'fitness-motivation-facebook-page-450k',
    title: 'Fitness Motivation Facebook Page — 450K Followers',
    category: 'Facebook Pages',
    category_slug: 'facebook-pages',
    price: 3200,
    monthly_revenue: 410,
    age_months: 34,
    verified: true,
    rating: 4.8,
    reviews_count: 22,
    views: 1830,
    cover_image: null,
    seller: { id: 11, name: 'Amara K.', verified: true, rating: 4.9 },
    created_at: '2026-06-02T10:00:00Z',
    summary: 'Highly engaged fitness page with organic reach and an active comment community.',
  },
  {
    id: 2,
    slug: 'travel-diaries-instagram-120k',
    title: 'Travel Diaries — Instagram, 120K Followers',
    category: 'Instagram Accounts',
    category_slug: 'instagram-accounts',
    price: 1850,
    monthly_revenue: 190,
    age_months: 21,
    verified: true,
    rating: 4.6,
    reviews_count: 14,
    views: 980,
    cover_image: null,
    seller: { id: 12, name: 'Yusuf D.', verified: true, rating: 4.7 },
    created_at: '2026-06-10T10:00:00Z',
    summary: 'Aesthetic travel niche account with strong story engagement and brand-deal history.',
  },
  {
    id: 3,
    slug: 'quickrecipes-tiktok-800k',
    title: 'QuickRecipes — TikTok, 800K Followers',
    category: 'TikTok Accounts',
    category_slug: 'tiktok-accounts',
    price: 5400,
    monthly_revenue: 620,
    age_months: 14,
    verified: true,
    rating: 4.9,
    reviews_count: 31,
    views: 2410,
    cover_image: null,
    seller: { id: 13, name: 'Lena P.', verified: true, rating: 5.0 },
    created_at: '2026-06-18T10:00:00Z',
    summary: 'Viral cooking shorts channel with consistent 1M+ monthly views.',
  },
  {
    id: 4,
    slug: 'devnotes-youtube-95k-subs',
    title: 'DevNotes — YouTube Channel, 95K Subscribers',
    category: 'YouTube Channels',
    category_slug: 'youtube-channels',
    price: 8900,
    monthly_revenue: 1150,
    age_months: 40,
    verified: true,
    rating: 4.7,
    reviews_count: 9,
    views: 1220,
    cover_image: null,
    seller: { id: 14, name: 'Ibrahim S.', verified: false, rating: 4.5 },
    created_at: '2026-05-28T10:00:00Z',
    summary: 'Monetized coding tutorials channel, fully demonetization-safe content.',
  },
  {
    id: 5,
    slug: 'minimalblog-content-website',
    title: 'MinimalBlog — Established Content Website',
    category: 'Websites',
    category_slug: 'websites',
    price: 12500,
    monthly_revenue: 940,
    age_months: 52,
    verified: true,
    rating: 4.8,
    reviews_count: 17,
    views: 1490,
    cover_image: null,
    seller: { id: 15, name: 'Sara M.', verified: true, rating: 4.8 },
    created_at: '2026-05-15T10:00:00Z',
    summary: 'SEO-optimized lifestyle blog with steady ad and affiliate income.',
  },
  {
    id: 6,
    slug: 'craftly-app-brandable-domain',
    title: 'craftly.app — Brandable Premium Domain',
    category: 'Domains',
    category_slug: 'domains',
    price: 950,
    monthly_revenue: 0,
    age_months: 6,
    verified: false,
    rating: null,
    reviews_count: 0,
    views: 340,
    cover_image: null,
    seller: { id: 16, name: 'Domain Vault', verified: true, rating: 4.6 },
    created_at: '2026-06-25T10:00:00Z',
    summary: 'Short, memorable .app domain — perfect for a creative tools startup.',
  },
  {
    id: 7,
    slug: 'habitloop-mobile-app-ios-android',
    title: 'HabitLoop — Habit Tracker App (iOS + Android)',
    category: 'Mobile Apps',
    category_slug: 'mobile-apps',
    price: 6700,
    monthly_revenue: 480,
    age_months: 18,
    verified: true,
    rating: 4.5,
    reviews_count: 11,
    views: 860,
    cover_image: null,
    seller: { id: 17, name: 'Nabil T.', verified: true, rating: 4.6 },
    created_at: '2026-06-05T10:00:00Z',
    summary: '4.7-star habit tracker with subscription revenue and low churn.',
  },
  {
    id: 8,
    slug: 'invoiceflow-saas-mrr',
    title: 'InvoiceFlow — Invoicing SaaS, $2.1K MRR',
    category: 'SaaS Projects',
    category_slug: 'saas-projects',
    price: 47000,
    monthly_revenue: 2100,
    age_months: 26,
    verified: true,
    rating: 4.9,
    reviews_count: 6,
    views: 2050,
    cover_image: null,
    seller: { id: 18, name: 'Chidi O.', verified: true, rating: 4.9 },
    created_at: '2026-05-30T10:00:00Z',
    summary: 'Lean invoicing SaaS for freelancers with clean codebase and stable churn.',
  },
];

export const MOCK_TOP_SELLERS = [
  { id: 11, name: 'Amara K.', rating: 4.9, sales: 38, verified: true },
  { id: 13, name: 'Lena P.', rating: 5.0, sales: 52, verified: true },
  { id: 18, name: 'Chidi O.', rating: 4.9, sales: 21, verified: true },
  { id: 15, name: 'Sara M.', rating: 4.8, sales: 29, verified: true },
]

export const MOCK_TESTIMONIALS = [
  {
    id: 1,
    name: 'Grace N.',
    role: 'Bought a YouTube channel',
    quote:
      'The escrow process made it feel completely safe. I never released funds without knowing the handover was verified.',
  },
  {
    id: 2,
    name: 'Tunde A.',
    role: 'Sold a SaaS product',
    quote:
      'Lawareeg took the awkwardness out of pricing and negotiating. Support was responsive at every step of the sale.',
  },
  {
    id: 3,
    name: 'Fatima R.',
    role: 'Bought an Instagram page',
    quote:
      'Clear instructions, transparent order status, and a real human reviewing my payment. Exactly what I needed.',
  },
]

export const MOCK_FAQS = [
  {
    q: 'How does the manual escrow process work?',
    a: 'When you buy an asset, you pay into Lawareeg via bank transfer or mobile money and upload your receipt. Our team verifies the payment, the seller transfers the asset, and funds are released only after you confirm you received it.',
  },
  {
    q: 'What happens if the seller never transfers the asset?',
    a: 'You can open a dispute at any point after payment confirmation. Our admin team reviews the case and can refund your payment if the seller fails to deliver.',
  },
  {
    q: 'How do I get paid as a seller?',
    a: 'Once the buyer confirms receipt of the asset, funds are released to your Lawareeg wallet minus our commission. You can then request a withdrawal to your bank or mobile money account.',
  },
  {
    q: 'Is there a fee to list an asset?',
    a: 'Listing is completely free. Lawareeg only charges a small commission on successfully completed sales.',
  },
  {
    q: 'How do I know a seller or buyer is trustworthy?',
    a: 'Verified sellers display a verification badge after completing our identity and ownership checks. You can also review ratings and past sales history before buying.',
  },
]
